spring:
  application:
    name: sysml-platform
    
  profiles:
    active: dev
    
  graphql:
    graphiql:
      enabled: true  # 仅在dev环境
    schema:
      printer:
        enabled: true
      introspection:
        enabled: ${GRAPHQL_INTROSPECTION_ENABLED:true}  # 生产环境设为false
        
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sysml_dev_db}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    root: INFO
    com.sysml.platform: DEBUG
    org.eclipse.emf.cdo: INFO
    graphql: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
# CDO配置
cdo:
  enabled: ${CDO_ENABLED:true}
  repository:
    name: sysml
    uuid: sysml-repo
  server:
    port: 2036
  lean:
    no-branches: true
    no-audits: true
    no-locks: true
  store:
    schema-name: ${CDO_SCHEMA_NAME:sysml}
    drop-on-activate: ${CDO_DROP_ON_ACTIVATE:false}
    
# 性能配置
performance:
  dataloader:
    batch-size: 100
    timeout: 5000
  query:
    max-depth: 10
    timeout: 5000
  mutation:
    timeout: 10000
    
# 缓存配置
cache:
  requirements:
    ttl: 300
    max-size: 1000

# Sirius配置
sirius:
  enabled: true
  web:
    enabled: true
    port: 3000
  cdo:
    integration: true
    repository: sysml
  modelers:
    path: classpath:sirius/modelers/
    auto-load: true
  views:
    - requirements
    - structure
    - behavior
    - parametrics