spring:
  datasource:
    url: jdbc:h2:./data/cdo-m2;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  graphql:
    graphiql:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health





