# 开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sysml_dev_db
    username: sysml_user
    password: sysml_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
# CDO配置
cdo:
  enabled: true
  repository:
    name: sysml
  server:
    port: 2036
  store:
    schema-name: sysml_cdo
    drop-on-activate: false  # CDO会自动管理schema
    
# 日志配置
logging:
  level:
    com.sysml: DEBUG
    org.eclipse.emf.cdo: DEBUG
    org.springframework: INFO